import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import { Header } from "../components/Header";
import { Suspense } from "react";
import Loading from "./loading";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Go Accounting",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <main className="flex min-h-screen flex-col items-center justify-between p-24">
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
